version: '3'
services:
  nvidia-llm:
    build: .
    environment:
      - NGC_API_KEY=${NGC_API_KEY}
      - HF_HOME=/hf_home
    volumes:
      - ${HF_HOME}:/hf_home
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]